---
name: POE-Component-NonBlockingWrapper-Base
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: POE based base class for non-blocking wrappers around blocking stuff
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.2222
  POE::Filter::Reference: 1.222
  POE::Wheel::Run: 1.2222
build_requires:
  Test::More: 0
provides:
  POE::Component::NonBlockingWrapper::Base:
    file: lib/POE/Component/NonBlockingWrapper/Base.pm
    version: 0.002
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
